backend:
  name: github
  repo: Hangar-31/atlantamusicians.com
  branch: staging-netlify

media_folder: static/assets
public_folder: /assets

collections:
  - name: pages
    label: Pages
    folder: src/pages
    create: true
    summary: "{{fields.title}} | Page Number: {{fields.number}} | Path: {{fields.path}}"
    sortableFields: ["title", "number", "path"]
    fields:
      - { name: path, label: Path }
      - { name: title, label: Title }
      - { name: number, label: Page Number }
      - label: Sections
        name: sections
        widget: list
        types:
            - label: Slideshow
              name: section_slideshow
              widget: object
              fields:
                - label: Slideshow Images
                  name: list
                  widget: list
                  fields:
                    - { label: Image, name: image, widget: image }
                    - { label: Image Alt Text, name: alt_text, widget: string }
            - label: Section - Bios
              name: section_bios
              widget: object
              fields:
                - { label: Alternate Row Colors, name: background_color_toggle, widget: "boolean", default: false, required: false }
                - label: Bio Items
                  name: list
                  widget: list
                  fields:
                    - { label: Name, name: name, widget: string }
                    - { label: Title, name: title, widget: string }
                    - { label: Bio, name: text, widget: text }
                    - { label: Bio Image, name: image, widget: image }
                    - { label: Bio Image Alt Text, name: alt_text, widget: string }
            - label: Content - Boxes
              name: section_content_boxes
              widget: object
              fields:
                - label: Box Items
                  name: list
                  widget: list
                  fields:
                    - { label: Title, name: title, widget: string }
                    - { label: Text, name: text, widget: text }
                    - { label: Image, name: image, widget: image }
                    - { label: Image Alt Text, name: alt_text, widget: string }
                    - { label: Link Text, name: link_text, widget: string }
                    - { label: Link URL, name: link_url, widget: string }
            - label: Content - Variant 1
              name: section_content_one
              widget: object
              fields:
                - { label: Title, name: title, widget: string }
                - { label: Text, name: text, widget: text }
                - { label: Image, name: image, widget: image }
                - { label: Image Alt Text, name: alt_text, widget: string }
                - { label: Image On Right, name: image_right, widget: "boolean", default: true, required: false}
                - { label: Link Text, name: link_text, widget: string, required: false }
                - { label: Link URL, name: link_url, widget: string, required: false }
                - { label: Add Background Color, name: background_color_toggle, widget: "boolean", default: false, required: false}
            - label: Banner
              name: section_banner
              widget: object
              fields:
                - { label: Title, name: title, widget: string }
                - { label: Content Image, name: content_image, widget: image }
                - { label: Content Image Alt Text, name: content_alt_text, widget: "string"}
                - { label: Content Title, name: content_title, widget: string, required: false }
                - { label: Content Text, name: content_text, widget: text, required: false }
                - { label: Link Text, name: link_text, widget: string, required: false }
                - { label: Link URL, name: link_url, widget: string, required: false }
            - label: Banner - Small
              name: section_banner_small
              widget: object
              fields:
                - { label: Title, name: title, widget: string }
                - { label: Text, name: text, widget: text }
                - { label: Image, name: image, widget: image }
                - { label: Image Alt Text, name: alt_text, widget: "string"}
                - { label: Link Text, name: link_text, widget: string, required: false }
                - { label: Link URL, name: link_url, widget: string, required: false }
                - { label: Add Red Background Color, name: background_color_toggle, widget: "boolean", default: false, required: false}
            - label: Title - Section
              name: section_title
              widget: object
              fields:
                - { label: Title, name: title, widget: string }
            - label: Content - Title 1
              name: section_content_title_1
              widget: object
              fields:
                - { label: Title, name: title, widget: string }
            - label: Content - Title 2
              name: section_content_title_2
              widget: object
              fields:
                - { label: Title, name: title, widget: string }
            - label: Content - Title 3
              name: section_content_title_3
              widget: object
              fields:
                - { label: Title, name: title, widget: string }
            - label: Content - Text
              name: section_content_text
              widget: object
              fields:
                - { label: Text, name: text, widget: text }
            - label: Content - Link
              name: section_content_link
              widget: object
              fields:
                - { label: Link Text, name: link_text, widget: string }
                - { label: Link URL, name: link_url, widget: string }
            - label: Content - Images
              name: section_content_images
              widget: object
              fields:
                - label: Content Images
                  name: list
                  widget: list
                  fields:
                    - { label: Image, name: image, widget: image }
                    - { label: Image Alt Text, name: alt_text, widget: string }